# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Anitya"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Blog chia sẻ về web và phát triển web"
homepage = "https://dangthanh.org/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Dang Van Thanh"
  homepage = "https://dangthanh.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
